---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-watch
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-watch-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - "soft"
    - "intr"
    - "timeo=2"
    - "retry=5"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ${STORAGE_CLASS_NAME}
  nfs:
    path: ${NFS_PATH}
    server: ${NFS_IP}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-watch-pvc
  namespace: nfs-watch
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nfs-watch-ds
  namespace: nfs-watch
spec:
  selector:
    matchLabels:
      name: nfs-watch
  template:
    metadata:
      labels:
        name: nfs-watch
    spec:
      containers:
        - name: nfs-watch-con
          image: nfs-watch:v1
          volumeMounts:
            - name: nfs-watch
              mountPath: /data/nfs-test
      volumes:
        - name: nfs-watch
          persistentVolumeClaim:
            claimName: nfs-watch-pvc